=== vkreal/xbkAPI/api/dhtml/doc/xml/tech_ref.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- edk descriptor dtd -->

<!-- root level tag: class -->
<!ELEMENT class (desc,fields,constructor?,methods?,related,examples,extends?) >
<!ATTLIST class
	name NMTOKEN #REQUIRED 
	version NMTOKEN #IMPLIED
	since NMTOKEN #IMPLIED 
	>
<!-- desc tag -->
<!ELEMENT desc (#PCDATA)>

<!-- fields tag -->
<!ELEMENT fields (param)* >

<!-- constructor -->
<!ELEMENT constructor (method)>



<!-- methods tag -->
<!ELEMENT methods (method)* >

	<!-- method tag -->
	<!ELEMENT method (method_desc,params,return?) >
	<!ATTLIST method
			name NMTOKEN #REQUIRED 
			comment CDATA #IMPLIED
		> 
	
		<!-- method_desc tag -->
		<!ELEMENT method_desc (#PCDATA) >
	
		<!-- params tag -->
		<!ELEMENT params (param)* >
			<!ELEMENT param EMPTY >
			<!ATTLIST param
				name NMTOKEN #REQUIRED 
				typename NMTOKEN #REQUIRED
				comment CDATA #IMPLIED
			>
		
		<!-- return tag -->
		<!ELEMENT return EMPTY >
		<!ATTLIST return
				typename NMTOKEN #REQUIRED
				comment CDATA #IMPLIED
		>

<!ELEMENT related (ref)* >
	<!ELEMENT ref EMPTY >
	<!ATTLIST ref
		url CDATA #REQUIRED 
		name NMTOKEN #REQUIRED 
		comment CDATA #IMPLIED
	>

<!ELEMENT examples (example)* >
	<!ELEMENT example EMPTY >
	<!ATTLIST example
		url CDATA #REQUIRED 
		title CDATA #REQUIRED
		comment CDATA #IMPLIED
	>	
						
<!ELEMENT extends EMPTY >
<!ATTLIST extends 
	name NMTOKEN #REQUIRED
>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkFileExplorer.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkFileExplorer" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkFileExplorer class provide a file explorer.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkFileExplorer" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkFileExplorer." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkFileExplorer object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="getParentNode" comment="" >
<method_desc>
<![CDATA[
Creates a parent xbkTreeNode Folder and return it.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="Text that appears for the item." />
<param name="fHandler" typename="Reference" comment="Reference to a handler function for this xbkTreeNode." />
<param name="closeImg" typename="String" comment="Image to use for folder close." />
<param name="openImg" typename="String" comment="Image to use for folder open." />
</params>
<return typename="xbkTreeNode" comment="Reference to a xbkTreeNode note: see xbkTreeNode class" ></return>
</method>
<method name="getChildNode" comment="" >
<method_desc>
<![CDATA[
Creates a child xbkTreeNode and return it.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="Text that appears for the item." />
<param name="fHandler" typename="Reference" comment="Reference to a handler function for this xbkTreeNode." />
<param name="img" typename="String" comment="Image to use." />
</params>
<return typename="xbkTreeNode" comment="Reference to a xbkTreeNode note: see xbkTreeNode class" ></return>
</method>
<method name="removeSelectedItem" comment="" >
<method_desc>
<![CDATA[
Remove the selected item.
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkMenuSystem.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkMenuSystem" version="1.1" since="1.0">
<desc>
<![CDATA[
The xbkMenuSystem class provides menu system for any xbkAPI web applications.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkMenuSystem" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkMenuSystem." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkMenuSystem object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="addRoot" comment="" >
<method_desc>
<![CDATA[
Add a root to the main menu system.
]]>
</method_desc>
<params>
<param name="sName" typename="Text" comment="to be use as name." />
<param name="fHandler" typename="Handler" comment="to be use when user click." />
</params>
<return typename="xbkMenu" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
</examples>
<extends name="xbkMenu" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkToolBar.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkToolBar" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkToolBar class provides a horizontal or vertical tool bar system.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkToolBar" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkToolBar." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkToolBar object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="autostrechHorizontal" comment="" >
<method_desc>
<![CDATA[
Autostrech horizontal.
]]>
</method_desc>
<params>
<param name="bType" typename="Boolean" comment="Set to true or false." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="autostrechVertical" comment="" >
<method_desc>
<![CDATA[
Autostrech vertical.
]]>
</method_desc>
<params>
<param name="bType" typename="Boolean" comment="Set to true or false." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setHorizontalToolBar" comment="" >
<method_desc>
<![CDATA[
Set Tool bar to be horizontal or vertical, default is horizontal.
]]>
</method_desc>
<params>
<param name="bType" typename="Boolean" comment="Set to true or false." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="addItem" comment="" >
<method_desc>
<![CDATA[
Adds an item to the Menu.
]]>
</method_desc>
<params>
<param name="img" typename="String" comment="Image to use." />
<param name="imgOver" typename="String" comment="Image for mouseover event." />
<param name="imgDown" typename="String" comment="Image for onclick event." />
<param name="fHandler" typename="Reference" comment="Referece to a handler function." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="removeItem" comment="" >
<method_desc>
<![CDATA[
Remove a item from the xbkToolBar
]]>
</method_desc>
<params>
<param name="index" typename="Number" comment="The index of the xbkToolBar to be remove." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="draw" comment="" >
<method_desc>
<![CDATA[
Draw the xbkToolBar
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkCGIPort.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkCGIPort" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkCGIPort provides CGI tasks that passes data back and forth and queing. The xbkCGIPort receives data from a CGI program and then directs that data to the correct function.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkCGIPort" comment="" >
<method_desc>  </method_desc>
<params>
<param name="target" typename="Refence" comment="Location on the cgi target." />
</params>
</method>
</constructor>
<methods>
<method name="add" comment="" >
<method_desc>
<![CDATA[
A new cgi call command object to the que.
]]>
</method_desc>
<params>
<param name="commandObj" typename="Command" comment="Command object created." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="command" comment="" >
<method_desc>
<![CDATA[
A new command object.
]]>
</method_desc>
<params>
</params>
<return typename="Object" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkObject" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkObject.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkObject" version="1.0" since="1.0">
<desc>
<![CDATA[
This class is an abstract class that is inherited by all xbkAPI classes.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkObject" comment="" >
<method_desc>  </method_desc>
<params>
<param name="type" typename="String" comment="The object that instantiated this class." />
<param name="ref" typename="Reference" comment="A reference to that object that has instantiated this abstract class." />
</params>
</method>
</constructor>
<methods>
<method name="getxbkObjectId" comment="" >
<method_desc>
<![CDATA[
Get current xbkObject id.
]]>
</method_desc>
<params>
</params>
<return typename="String" comment="" ></return>
</method>
<method name="getxbkObjectById" comment="" >
<method_desc>
<![CDATA[
Get xbkObject by id.
]]>
</method_desc>
<params>
<param name="id" typename="String" comment="The id xbkObject to find." />
</params>
<return typename="xbkObject" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="null" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkTab.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkTab" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkTab class provides Tab Seletion options for xbkAPI web applications.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkMenu" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkTab." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkTab object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="addItem" comment="" >
<method_desc>
<![CDATA[
Adds an item to the Tab.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="Text that appears for the item." />
<param name="fHandler" typename="Reference" comment="Referece to a handler function." />
</params>
<return typename="xbkLayer" comment="The body as a xbkLayer" ></return>
</method>
<method name="remove" comment="" >
<method_desc>
<![CDATA[
Remove an item from the Tab.
]]>
</method_desc>
<params>
<param name="index" typename="Number" comment="Index of tab." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setTabBgColor" comment="" >
<method_desc>
<![CDATA[
Set the background color of the tab when click on and off.
]]>
</method_desc>
<params>
<param name="sTabOn" typename="String" comment="Color when this tab has focus" />
<param name="sTabOff" typename="String" comment="Color when this tab is off focus" />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="redraw" comment="" >
<method_desc>
<![CDATA[
Redraw xbkTab.
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkDragAndDrop.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkDragAndDrop" version="1.0" since="1.0">
<desc>
<![CDATA[
This xbkDragAndDrop class handles the drag and drop event for the xbkAPI Class Object.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkDragAndDrop" comment="" >
<method_desc>  </method_desc>
<params>
</params>
</method>
</constructor>
<methods>
<method name="setDragIconBgColor" comment="" >
<method_desc>
<![CDATA[
Set the icon drag background color.
]]>
</method_desc>
<params>
<param name="sColor" typename="String" comment="color to be use." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setUseImageAsDragIcon" comment="" >
<method_desc>
<![CDATA[
Use the image as the drag icon.
]]>
</method_desc>
<params>
<param name="bSet" typename="Boolean" comment="" />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setSelectItem" comment="" >
<method_desc>
<![CDATA[
Set the select item.
]]>
</method_desc>
<params>
<param name="node" typename="Variant" comment="" />
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkObject" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkPopupMenu.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkPopupMenu" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkPopupMenu class provides a menu system.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkPopupMenu" comment="" >
<method_desc>  </method_desc>
<params>
<param name="parent" typename="xbkLayer" comment="The parent of the xbkPopupMenu object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="addItem" comment="" >
<method_desc>
<![CDATA[
Adds an item to the Menu.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="Text that appears for the item." />
<param name="fHandler" typename="Reference" comment="Referece to a handler function." />
</params>
<return typename="Nothing" comment="" ></return>
</method>
<method name="addBar" comment="" >
<method_desc>
<![CDATA[
Adds a separator to divide groups of menu commands.
]]>
</method_desc>
<params>
</params>
<return typename="Nothing" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
</examples>
<extends name="xbkLayer" />
</class>
