=== vkreal/xbkAPI/api/dhtml/doc/xml/tech_ref.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- edk descriptor dtd -->

<!-- root level tag: class -->
<!ELEMENT class (desc,fields,constructor?,methods?,related,examples,extends?) >
<!ATTLIST class
	name NMTOKEN #REQUIRED 
	version NMTOKEN #IMPLIED
	since NMTOKEN #IMPLIED 
	>
<!-- desc tag -->
<!ELEMENT desc (#PCDATA)>

<!-- fields tag -->
<!ELEMENT fields (param)* >

<!-- constructor -->
<!ELEMENT constructor (method)>



<!-- methods tag -->
<!ELEMENT methods (method)* >

	<!-- method tag -->
	<!ELEMENT method (method_desc,params,return?) >
	<!ATTLIST method
			name NMTOKEN #REQUIRED 
			comment CDATA #IMPLIED
		> 
	
		<!-- method_desc tag -->
		<!ELEMENT method_desc (#PCDATA) >
	
		<!-- params tag -->
		<!ELEMENT params (param)* >
			<!ELEMENT param EMPTY >
			<!ATTLIST param
				name NMTOKEN #REQUIRED 
				typename NMTOKEN #REQUIRED
				comment CDATA #IMPLIED
			>
		
		<!-- return tag -->
		<!ELEMENT return EMPTY >
		<!ATTLIST return
				typename NMTOKEN #REQUIRED
				comment CDATA #IMPLIED
		>

<!ELEMENT related (ref)* >
	<!ELEMENT ref EMPTY >
	<!ATTLIST ref
		url CDATA #REQUIRED 
		name NMTOKEN #REQUIRED 
		comment CDATA #IMPLIED
	>

<!ELEMENT examples (example)* >
	<!ELEMENT example EMPTY >
	<!ATTLIST example
		url CDATA #REQUIRED 
		title CDATA #REQUIRED
		comment CDATA #IMPLIED
	>	
						
<!ELEMENT extends EMPTY >
<!ATTLIST extends 
	name NMTOKEN #REQUIRED
>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkIconBrowser.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkIconBrowser" version="2.1" since="1.0">
<desc>
<![CDATA[
The xbkIconBrowser Class creates a file view like look and feel tool for any xbkAPI web applications.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkIconView" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkIconBrowser." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkIconBrowser object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="removeALL" comment="" >
<method_desc>
<![CDATA[
Remove all.
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setHighLightColor" comment="" >
<method_desc>
<![CDATA[
Set the highlight selected color.
]]>
</method_desc>
<params>
<param name="color" typename="String" comment="Color to be use." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="addItem" comment="" >
<method_desc>
<![CDATA[
Adds an icon to the xbkIconBrowser.
]]>
</method_desc>
<params>
<param name="id" typename="String" comment="icon id." />
<param name="text" typename="String" comment="Display name of the icon." />
<param name="img" typename="URL" comment="of the icon image to display." />
<param name="fHandler" typename="Reference" comment="A Function handler to be use by this icon." />
</params>
<return typename="Nothing" comment="" ></return>
</method>
<method name="getSelectedId" comment="" >
<method_desc>
<![CDATA[
Returns the id of the icon currently selected, null if none.
]]>
</method_desc>
<params>
</params>
<return typename="String" comment="" ></return>
</method>
<method name="removeItem" comment="" >
<method_desc>
<![CDATA[
Remove an item from the xbkIconBrowser.
]]>
</method_desc>
<params>
<param name="id" typename="String" comment="id of the icon to remove." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="sort" comment="" >
<method_desc>
<![CDATA[
Organizes all in descending alphabetical order by name.
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
<method name="selectIconById" comment="" >
<method_desc>
<![CDATA[
Select an item from the xbkIconBrowser.
]]>
</method_desc>
<params>
<param name="id" typename="String" comment="id of the icon to select." />
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkLayer" />
</class>
