=== vkreal/xbkAPI/api/dhtml/doc/xml/tech_ref.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- edk descriptor dtd -->

<!-- root level tag: class -->
<!ELEMENT class (desc,fields,constructor?,methods?,related,examples,extends?) >
<!ATTLIST class
	name NMTOKEN #REQUIRED 
	version NMTOKEN #IMPLIED
	since NMTOKEN #IMPLIED 
	>
<!-- desc tag -->
<!ELEMENT desc (#PCDATA)>

<!-- fields tag -->
<!ELEMENT fields (param)* >

<!-- constructor -->
<!ELEMENT constructor (method)>



<!-- methods tag -->
<!ELEMENT methods (method)* >

	<!-- method tag -->
	<!ELEMENT method (method_desc,params,return?) >
	<!ATTLIST method
			name NMTOKEN #REQUIRED 
			comment CDATA #IMPLIED
		> 
	
		<!-- method_desc tag -->
		<!ELEMENT method_desc (#PCDATA) >
	
		<!-- params tag -->
		<!ELEMENT params (param)* >
			<!ELEMENT param EMPTY >
			<!ATTLIST param
				name NMTOKEN #REQUIRED 
				typename NMTOKEN #REQUIRED
				comment CDATA #IMPLIED
			>
		
		<!-- return tag -->
		<!ELEMENT return EMPTY >
		<!ATTLIST return
				typename NMTOKEN #REQUIRED
				comment CDATA #IMPLIED
		>

<!ELEMENT related (ref)* >
	<!ELEMENT ref EMPTY >
	<!ATTLIST ref
		url CDATA #REQUIRED 
		name NMTOKEN #REQUIRED 
		comment CDATA #IMPLIED
	>

<!ELEMENT examples (example)* >
	<!ELEMENT example EMPTY >
	<!ATTLIST example
		url CDATA #REQUIRED 
		title CDATA #REQUIRED
		comment CDATA #IMPLIED
	>	
						
<!ELEMENT extends EMPTY >
<!ATTLIST extends 
	name NMTOKEN #REQUIRED
>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkLabel.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkLabel" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkLabel class provides simple labels for any xbkAPI web applications.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkLabel" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkLabel." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkLabel object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="setTextAlign" comment="" >
<method_desc>
<![CDATA[
Set the text align.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="" />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setText" comment="" >
<method_desc>
<![CDATA[
Set the text for the xbkLabel.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="" />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setStyle" comment="" >
<method_desc>
<![CDATA[
Set the CSS style.
]]>
</method_desc>
<params>
<param name="sStyle" typename="String" comment="Class style name." />
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkMenu.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkMenu" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkMenu class provides a horizontal or vertical menu system.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkMenu" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkMenu." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkMenu object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="hideALLxbkMenu" comment="" >
<method_desc>
<![CDATA[
Hide all the xbkMenu.
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
<method name="autostrechHorizontal" comment="" >
<method_desc>
<![CDATA[
Autostrech horizontal.
]]>
</method_desc>
<params>
<param name="bType" typename="Boolean" comment="Set to true or false." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="autostrechVertical" comment="" >
<method_desc>
<![CDATA[
Autostrech vertical.
]]>
</method_desc>
<params>
<param name="bType" typename="Boolean" comment="Set to true or false." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setVis" comment="" >
<method_desc>
<![CDATA[
Set the xbkMenu visibility and x,y location.
]]>
</method_desc>
<params>
<param name="type" typename="String" comment="[show|hidden|inherit]" />
<param name="x" typename="Number" comment="location x" />
<param name="y" typename="Number" comment="location y" />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setHorizontalMenu" comment="" >
<method_desc>
<![CDATA[
Set menu to be horizontal or vertical, default is horizontal.
]]>
</method_desc>
<params>
<param name="bType" typename="Boolean" comment="Set to true or false." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="addItem" comment="" >
<method_desc>
<![CDATA[
Adds an item to the Menu.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="Text that appears for the item." />
<param name="fHandler" typename="Reference" comment="Referece to a handler function." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="addBar" comment="" >
<method_desc>
<![CDATA[
Adds a separator to divide groups of menu commands.
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setMouseOverHightLight" comment="" >
<method_desc>
<![CDATA[
Set the mouseover event to hightlight the selections.
]]>
</method_desc>
<params>
<param name="bType" typename="Boolean" comment="" />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="draw" comment="" >
<method_desc>
<![CDATA[
Draw the xbkMenu
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkProgressBar.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkProgressBar" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkProgressBar class provides visual feedback to users about the progress of task, such as loading an application or querying a database.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkProgressBar" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkProgressBar." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkProgressBar object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="setStyleClass" comment="" >
<method_desc>
<![CDATA[
Set the style className for the current xbkProgessBar
]]>
</method_desc>
<params>
<param name="startStyleClass" typename="String" comment="The style class name for the start." />
<param name="endStyleClass" typename="String" comment="The style class name for the end." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setPercentComplete" comment="" >
<method_desc>
<![CDATA[
Set the percentage of completion.
]]>
</method_desc>
<params>
<param name="num" typename="Number" comment="Use the number 1-100 to represent the percent." />
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkWindow.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkWindow" version="1.1" since="1.0">
<desc>
<![CDATA[
The xbkWindow Class creates a window like look and feel tool for any xbkAPI web applications.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkWindow" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkWindow." />
<param name="parent" typename="xbkLayer" comment="The windows parent, if any." />
</params>
</method>
</constructor>
<methods>
<method name="setWindowTitle" comment="" >
<method_desc>
<![CDATA[
Set the title and style for the xbkWindow.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="Text for the title." />
<param name="style" typename="String" comment="The class style name." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setCloseWindowHandler" comment="" >
<method_desc>
<![CDATA[
Set the close window handler.
]]>
</method_desc>
<params>
<param name="func" typename="Handler" comment="Handler to be call when the window close." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setMinWindowHandler" comment="" >
<method_desc>
<![CDATA[
Set the minimize window handler.
]]>
</method_desc>
<params>
<param name="func" typename="Handler" comment="Handler to be call when the window minimize." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setMaxWindowHandler" comment="" >
<method_desc>
<![CDATA[
Set the maximize window handler.
]]>
</method_desc>
<params>
<param name="func" typename="Handler" comment="Handler to be call when the window maximize." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="setIconWinHandler" comment="" >
<method_desc>
<![CDATA[
Set the icon click handler.
]]>
</method_desc>
<params>
<param name="func" typename="Handler" comment="Handler to be call when the icon is click." />
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkTree.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkTree" version="1.2" since="1.0">
<desc>
<![CDATA[
The xbkTree class display information in a hierarchal tree system.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkTree" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkMenu." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkMenu object if it has one." />
</params>
</method>
</constructor>
<methods>
<method name="getSelectedNode" comment="" >
<method_desc>
<![CDATA[
Get the current selected xbkTreeNode.
]]>
</method_desc>
<params>
</params>
<return typename="xbkTreeNode" comment="" ></return>
</method>
<method name="setImagePath" comment="" >
<method_desc>
<![CDATA[
Set the path for the image location folder.
]]>
</method_desc>
<params>
<param name="path" typename="String" comment="location of images folder." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="getChildNode" comment="" >
<method_desc>
<![CDATA[
Creates a child xbkTreeNode and return it.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="Text that appears for the item." />
<param name="fHandler" typename="Reference" comment="Reference to a handler function for this xbkTreeNode." />
<param name="img" typename="String" comment="Image to use." />
</params>
<return typename="xbkTreeNode" comment="Reference to a xbkTreeNode note: see xbkTreeNode class" ></return>
</method>
<method name="getParentNode" comment="" >
<method_desc>
<![CDATA[
Creates a parent xbkTreeNode and return it.
]]>
</method_desc>
<params>
<param name="text" typename="String" comment="Text that appears for the item." />
<param name="fHandler" typename="Reference" comment="Reference to a handler function for this xbkTreeNode." />
<param name="closeImg" typename="String" comment="Image to use for folder close." />
<param name="openImg" typename="String" comment="Image to use for folder open." />
</params>
<return typename="xbkTreeNode" comment="Reference to a xbkTreeNode note: see xbkTreeNode class" ></return>
</method>
<method name="addRoot" comment="" >
<method_desc>
<![CDATA[
Add a root xbkTreeNode to the current xbkTree.
]]>
</method_desc>
<params>
<param name="node" typename="xbkTreeNode" comment="A xbkTreeNode to be added to the root level." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="removeNode" comment="" >
<method_desc>
<![CDATA[
Remove a node by id from the current xbkTree.
]]>
</method_desc>
<params>
<param name="id" typename="String" comment="" />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="draw" comment="" >
<method_desc>
<![CDATA[
Draw the xbkTree.
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkDragEvent.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkDragEvent" version="1.0" since="1.0">
<desc>
<![CDATA[
This xbkDragEvent class handles the drag event for the xbkLayer Class Object.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkDragEvent" comment="" >
<method_desc>  </method_desc>
<params>
</params>
</method>
</constructor>
<methods>
<method name="getDragxbkLayerById" comment="" >
<method_desc>
<![CDATA[
Get the Draggable xbkLayer by id.
]]>
</method_desc>
<params>
</params>
<return typename="xbkLayer" comment="" ></return>
</method>
<method name="getAppWidth" comment="" >
<method_desc>
<![CDATA[
Get the current application window width.
]]>
</method_desc>
<params>
</params>
<return typename="Number" comment="" ></return>
</method>
<method name="getAppHeight" comment="" >
<method_desc>
<![CDATA[
Get the current application window width.
]]>
</method_desc>
<params>
</params>
<return typename="Number" comment="" ></return>
</method>
<method name="setBoundedByWindow" comment="" >
<method_desc>
<![CDATA[
set the drag boundary to the current window.
]]>
</method_desc>
<params>
<param name="bool" typename="Boolean" comment="" />
</params>
<return typename="Nothing" comment="" ></return>
</method>
<method name="enableDragEvent" comment="" >
<method_desc>
<![CDATA[
enable a drag event
]]>
</method_desc>
<params>
<param name="obj" typename="xbkLayer" comment="a reference to a xbkLayer" />
</params>
<return typename="Nothing" comment="" ></return>
</method>
<method name="disableDragEvent" comment="" >
<method_desc>
<![CDATA[
disable a drag event for a specific xbkLayer.
]]>
</method_desc>
<params>
<param name="obj" typename="xbkLayer" comment="a reference to a xbkLayer" />
</params>
<return typename="Nothing" comment="" ></return>
</method>
<method name="setBoundedToParent" comment="" >
<method_desc>
<![CDATA[
set bounded to parent, so when sibling is move the parent moves too
]]>
</method_desc>
<params>
<param name="bool" typename="Boolean" comment="" />
</params>
<return typename="Nothing" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkObject" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkList.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkList" version="1.0" since="1.0">
<desc>
<![CDATA[
The xbkList class display information in a list type system.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkList" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkList." />
<param name="parent" typename="xbkLayer" comment="The parent of the xbkList object." />
</params>
</method>
</constructor>
<methods>
<method name="setSelectedColor" comment="" >
<method_desc>
<![CDATA[
Set the background color of the selected row.
]]>
</method_desc>
<params>
<param name="color" typename="String" comment="The color to use." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="aHeading" comment="" >
<method_desc>
<![CDATA[
Set the heading of the xbkList.
]]>
</method_desc>
<params>
<param name="aHeading" typename="Array" comment="The heading to be use." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="addRow" comment="" >
<method_desc>
<![CDATA[
Set a row to the xbkList.
]]>
</method_desc>
<params>
<param name="id" typename="String" comment="A unique id for the row." />
<param name="aRow" typename="Array" comment="The row html string." />
<param name="fhandler" typename="Reference" comment="A reference to a function handler for the row." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="removeRow" comment="" >
<method_desc>
<![CDATA[
Remove the row by id.
]]>
</method_desc>
<params>
<param name="id" typename="String" comment="A unique id for the row." />
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkLayer" />
</class>

=== vkreal/xbkAPI/api/dhtml/doc/xml/xbkScroll.xml
<?xml version='1.0'?>
<!DOCTYPE class SYSTEM "tech_ref.dtd">
<class name="xbkScroll" version="2.1" since="1.0">
<desc>
<![CDATA[
The xbkScroll Class creates xbkLayer that scroll with the browser.
]]>
</desc>
<fields>
</fields>
<constructor>
<method name="xbkScroll" comment="" >
<method_desc>  </method_desc>
<params>
<param name="inst" typename="String" comment="The name or id to be use for this xbkScroll." />
<param name="xbkLayerObj" typename="xbkLayer" comment="The xbkLayer to scroll." />
</params>
</method>
</constructor>
<methods>
<method name="setScrollDelay" comment="" >
<method_desc>
<![CDATA[
Set the scroll delay.
]]>
</method_desc>
<params>
<param name="num" typename="Number" comment="Scroll delay in milliseconds." />
</params>
<return typename="None" comment="" ></return>
</method>
<method name="scroll" comment="" >
<method_desc>
<![CDATA[
Start the scroll.
]]>
</method_desc>
<params>
</params>
<return typename="None" comment="" ></return>
</method>
</methods>
<related>
</related>
<examples>
<example url="pathToExampleFile" title="exampleTitle" comment="exampleComment" />
</examples>
<extends name="xbkObject" />
</class>
